#!/bin/bash

################################################# 変数定義
repo='http://192.168.1.61/svn/configs/'
hostname='redmine-trunk2'
svn='/usr/bin/svn'
tmp='/tmp/regdirsvn'
wd=`pwd`      # ワークディレクトリのフルパス
twd=${wd##*/} # ワークディレクトリ名の最後の名前
rwd=$repo$hostname$wd  # SVNへのURL

echo -n 'SVN user: '
read user
############################################ SVNフォルダ作成
declare -a addFolder
search=$rwd

if ! $svn ls --username $user $repo > /dev/null; then
  echo 'ERROR: Can not connect SVN server.'
  exit
fi

# SVNに存在しているフォルダを探索
while ! $svn --username $user ls $search >/dev/null; do
  echo search= $search
  addFolder=($search "${addFolder[@]}")
  search=${search%/*}
done

basePath=$tmp'/'${search##*/}
echo basePath: $basePath

if [ ! -e $tmp ]; then
  mkdir $tmp # 作業フォルダがなければ作る
fi

if [ -e $basePath ]; then
  echo ERROR: work folder already exist: $basePath
  exit
fi

echo
echo '>' mkdir $basePath
mkdir $basePath

echo
echo '>' $svn checkout --username $user -N $search $basePath
$svn checkout --username $user -N $search $basePath || exit

newPath=$basePath
# 不足していたフォルダを順に作成
for newURL in "${addFolder[@]}"; do
  newPath=$basePath${newURL#$search}
  echo
  echo '>' $svn mkdir --username $user $newPath
  $svn mkdir --username $user $newPath || exit
done

# 作成したフォルダをコミット
echo
echo '>' $svn commit --username $user -m 'regdirsvn' $basePath
$svn commit --username $user -m 'regdirsvn' $basePath || exit # コミット

# 古い.svnがあれば削除
if [ -e $wd'/.svn' ]; then
  echo
  echo '>' rm -rf $wd'/.svn'
  rm -rf $wd'/.svn'
fi

# .svnゲット
echo
echo '>' mv $newPath'/.svn' $wd'/.svn'
mv $newPath'/.svn' $wd'/.svn'

# 掃除して終了
echo
echo '>' rm -rf $basePath
rm -rf $basePath
