#!/bin/bash

config='/usr/local/etc/regdirsvn/regdirsvn.conf'

if ! source $config; then
  echo "Can not open config file: $config"
  exit
fi

############################## 登録されている全Dirについてsvn status -qu を実行
export LANG=C # 言語設定が異なるとsvn statusの実行結果が異なるため
while read svndir;do
  echo "check: "$svndir
  cd $svndir
  $svn status -qu | egrep -v '^Status against revision:' > $recDir$svndir'/check'
done < $regFile
